/*
 * This source file was generated by the Gradle 'init' task
 */
package introducaoprogramacaofurb2026.beecrowd20260315;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        introducaoprogramacaofurb2026.beecrowd20260315.Exercicios.NotasEMoedas.notasEMoedas();
    }
}
